name: travel_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  user_repository:
    path: packages/user_repository
  city_repository:
    path: packages/city_repository
  place_repository:
    path: packages/place_repository
  trip_repository:
    path: packages/trip_repository

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.7.0
  firebase_core: ^2.24.2
  equatable: ^2.0.5
  carousel_slider: ^4.2.1
  readmore: ^2.2.0
  google_maps_flutter: ^2.5.3
  stream_transform: ^2.1.0
  bloc_concurrency: ^0.2.4
  custom_info_window: ^1.0.1
  go_router: ^13.2.0
  flutter_config: ^2.0.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  latlong2: ^0.9.1
  uuid: ^4.2.2
  image_picker: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/styles/
    
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 800